# Generated by Django 6.0 on 2025-12-10 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='number_payment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='payment_method',
            field=models.CharField(choices=[('payment_on_delivery', 'Payment on Delivery'), ('mpesa', 'Mpesa'), ('card', 'Card Payment')], max_length=200, null=True),
        ),
    ]
