# Generated by Django 6.0 on 2025-12-11 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_shippingaddress_product_shippingaddress_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Delivered', 'Delivered')], default='Pending', max_length=20),
        ),
    ]
